(ns com.adgoji.mollie.link
  (:require
   [clojure.spec.alpha :as s]))

(s/def ::href string?)
(s/def ::type string?)
(s/def ::link (s/nilable (s/keys :req [::href ::type])))
(s/def ::dashboard ::link)
(s/def ::documentation ::link)
(s/def ::self ::link)
(s/def ::checkout ::link)
(s/def ::mobile-app-checkout ::link)
(s/def ::refunds ::link)
(s/def ::chargebacks ::link)
(s/def ::captures ::link)
(s/def ::settlement ::link)
(s/def ::order ::link)
(s/def ::mandate ::link)
(s/def ::mandates ::link)
(s/def ::subscription ::link)
(s/def ::subscriptions ::link)
(s/def ::payment ::link)
(s/def ::payments ::link)
(s/def ::customer ::link)
(s/def ::change-payment-state ::link)
(s/def ::profile ::link)
(s/def ::product-url ::link)
(s/def ::image-url ::link)
