name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test-clj:
    runs-on: ubuntu-latest
    env:
      MOLLIE_API_KEY: ${{ secrets.MOLLIE_API_KEY }}
      MOLLIE_PARTNER_ID: ${{ secrets.MOLLIE_PARTNER_ID }}
      MOLLIE_PROFILE_ID: ${{ secrets.MOLLIE_PROFILE_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 'latest'
          bb: 'latest'

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          restore-keys: cljdeps-

      - run: bb test

  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: DeLaGuardo/setup-clojure@master
        with:
          clj-kondo: 'latest'
          bb: 'latest'

      - uses: actions/checkout@v3

      - run: bb lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cljfmt: 'latest'
          bb: 'latest'

      - run: bb format:check
